# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinOsc.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_oscillWindow(object):
    def setupUi(self, oscillWindow):
        oscillWindow.setObjectName("oscillWindow")
        oscillWindow.resize(870, 750)
        self.centralwidget = QtWidgets.QWidget(oscillWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.idnLabel = QtWidgets.QLabel(self.centralwidget)
        self.idnLabel.setTextFormat(QtCore.Qt.RichText)
        self.idnLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.idnLabel.setObjectName("idnLabel")
        self.horizontalLayout_2.addWidget(self.idnLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lxiRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.lxiRadio.setChecked(True)
        self.lxiRadio.setObjectName("lxiRadio")
        self.horizontalLayout.addWidget(self.lxiRadio)
        self.lxiCombo = QtWidgets.QComboBox(self.centralwidget)
        self.lxiCombo.setMinimumSize(QtCore.QSize(200, 30))
        self.lxiCombo.setEditable(True)
        self.lxiCombo.setObjectName("lxiCombo")
        self.horizontalLayout.addWidget(self.lxiCombo)
        self.rs232Radio = QtWidgets.QRadioButton(self.centralwidget)
        self.rs232Radio.setObjectName("rs232Radio")
        self.horizontalLayout.addWidget(self.rs232Radio)
        self.rs232Combo = QtWidgets.QComboBox(self.centralwidget)
        self.rs232Combo.setEnabled(False)
        self.rs232Combo.setObjectName("rs232Combo")
        self.horizontalLayout.addWidget(self.rs232Combo)
        self.usbtmcRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.usbtmcRadio.setObjectName("usbtmcRadio")
        self.horizontalLayout.addWidget(self.usbtmcRadio)
        self.usbtmcCombo = QtWidgets.QComboBox(self.centralwidget)
        self.usbtmcCombo.setEnabled(False)
        self.usbtmcCombo.setObjectName("usbtmcCombo")
        self.horizontalLayout.addWidget(self.usbtmcCombo)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.oscilloscopeTab = QtWidgets.QWidget()
        self.oscilloscopeTab.setObjectName("oscilloscopeTab")
        self.oscillographPlot = QtWidgets.QWidget(self.oscilloscopeTab)
        self.oscillographPlot.setGeometry(QtCore.QRect(260, 20, 541, 351))
        self.oscillographPlot.setObjectName("oscillographPlot")
        self.tabWidget.addTab(self.oscilloscopeTab, "")
        self.parametersTab = QtWidgets.QWidget()
        self.parametersTab.setObjectName("parametersTab")
        self.gridLayout = QtWidgets.QGridLayout(self.parametersTab)
        self.gridLayout.setObjectName("gridLayout")
        self.rs232Widget = serialPortWidget(self.parametersTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rs232Widget.sizePolicy().hasHeightForWidth())
        self.rs232Widget.setSizePolicy(sizePolicy)
        self.rs232Widget.setMinimumSize(QtCore.QSize(0, 30))
        self.rs232Widget.setObjectName("rs232Widget")
        self.gridLayout.addWidget(self.rs232Widget, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 238, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.parametersTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 2)
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setObjectName("quitButton")
        self.gridLayout_2.addWidget(self.quitButton, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(765, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 1)
        oscillWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(oscillWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 35))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        oscillWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(oscillWindow)
        self.statusbar.setObjectName("statusbar")
        oscillWindow.setStatusBar(self.statusbar)
        self.actionQuit_Ctrl_Q = QtWidgets.QAction(oscillWindow)
        self.actionQuit_Ctrl_Q.setObjectName("actionQuit_Ctrl_Q")
        self.menuFile.addAction(self.actionQuit_Ctrl_Q)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(oscillWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(oscillWindow)

    def retranslateUi(self, oscillWindow):
        _translate = QtCore.QCoreApplication.translate
        oscillWindow.setWindowTitle(_translate("oscillWindow", "Oscilloscope"))
        self.label.setText(_translate("oscillWindow", "Oscilloscope:"))
        self.idnLabel.setText(_translate("oscillWindow", "<html><head/><body><p><span style=\" font-weight:600;\">If it is connected, IDN will be shown here.</span></p></body></html>"))
        self.lxiRadio.setText(_translate("oscillWindow", "LXI?"))
        self.rs232Radio.setText(_translate("oscillWindow", "RS232?"))
        self.usbtmcRadio.setText(_translate("oscillWindow", "USBTMC?"))
        self.connectButton.setText(_translate("oscillWindow", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.oscilloscopeTab), _translate("oscillWindow", "Oscillloscope"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.parametersTab), _translate("oscillWindow", "Parameters"))
        self.quitButton.setText(_translate("oscillWindow", "Quit"))
        self.menuFile.setTitle(_translate("oscillWindow", "File"))
        self.actionQuit_Ctrl_Q.setText(_translate("oscillWindow", "Quit(Ctrl+Q)"))

from GUI.serialPortWidget.serialPortWidget import serialPortWidget
